# Generated by Django 4.1 on 2022-12-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='d', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
