# Generated by Django 4.1 on 2022-12-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
    ]
